In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

DataFram = sns.load_dataset('tips')
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

print("-> HERE IS 'tips' LOADED DATASET:")
DataFram.head()

-> HERE IS 'tips' LOADED DATASET:

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
dummy_datafram = pd.get_dummies(DataFram)
print("-> ENCODING OR CREATE DUMMIES COLS FOR CATEFORICAL VALUEs:")
dummy_datafram.head()

# pd.get_dummies(DataFram, prefix=None, prefix_sep="_", dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None).head()

-> ENCODING OR CREATE DUMMIES COLS FOR CATEFORICAL VALUEs:

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,False,True,False,True,False,False,False,True,False,True
1,10.34,1.66,3,True,False,False,True,False,False,False,True,False,True
2,21.01,3.50,3,True,False,False,True,False,False,False,True,False,True
3,23.68,3.31,2,True,False,False,True,False,False,False,True,False,True
4,24.59,3.61,4,False,True,False,True,False,False,False,True,False,True

In [ ]:
dummy_day = pd.get_dummies(DataFram['day'])
dummy_sex = pd.get_dummies(DataFram['sex'])
dummy_smoker = pd.get_dummies(DataFram['smoker'])
dummy_time = pd.get_dummies(DataFram['time'])

print("-> SHOW PERTICULAR CATEGORICAL COLUMNS:")
display(dummy_day.head())
# display(dummy_sex.head())
# display(dummy_smoker.head())
# display(dummy_time.head())


dummy_sex_change = pd.get_dummies(DataFram['sex'], prefix='gender')
print("\n\n-> CHANGE ANY COLUMNS NAMES FOR BETTER LABELS:")
display(dummy_sex_change.head())

-> SHOW PERTICULAR CATEGORICAL COLUMNS:

    Thur    Fri    Sat   Sun
0  False  False  False  True
1  False  False  False  True
2  False  False  False  True
3  False  False  False  True
4  False  False  False  True

-> CHANGE ANY COLUMNS NAMES FOR BETTER LABELS:

   gender_Male  gender_Female
0        False           True
1         True          False
2         True          False
3         True          False
4        False           True

In [ ]:
# dummy_firstdrop = pd.get_dummies(DataFram, drop_first=True)
# print("-> NOW WE DROP FIRST DUMMIE COLS FOR BETTER UNDERSTANDING:")
# dummy_firstdrop.head()

In [ ]:
print("-> ONLY ENCODE SPECIFIC COLUMNS, LEAVE OTHER AS-IS:")
display(pd.get_dummies(DataFram, columns=['sex', 'smoker']).head())

-> ONLY ENCODE SPECIFIC COLUMNS, LEAVE OTHER AS-IS:

,total_bill,tip,day,time,size,sex_Male,sex_Female,smoker_Yes,smoker_No
0,16.99,1.01,Sun,Dinner,2,False,True,False,True
1,10.34,1.66,Sun,Dinner,3,True,False,False,True
2,21.01,3.50,Sun,Dinner,3,True,False,False,True
3,23.68,3.31,Sun,Dinner,2,True,False,False,True
4,24.59,3.61,Sun,Dinner,4,False,True,False,True

In [ ]:
print("=> METHOD 2: SCIKIT-LEANR ONEHOTENCODER (THE PROFESSIONAL WAY):\n")

oh_encoder = OneHotEncoder(sparse_output=False)

print("-> GRAB AND SELECT ONLY CATEGORICAL DATAs (COLUMNS):")
categorical_data = DataFram[['sex', 'smoker', 'day', 'time']]
categorical_data.head()

=> METHOD 2: SCIKIT-LEANR ONEHOTENCODER (THE PROFESSIONAL WAY):

-> GRAB AND SELECT ONLY CATEGORICAL DATAs (COLUMNS):

      sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

In [ ]:
print("-> APPLY ONE-HOT ENCODING:")
encoded_arr = oh_encoder.fit_transform(categorical_data)
display(encoded_arr)

-> APPLY ONE-HOT ENCODING:

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [ ]:
print("-> GET THE FEATURE NAMES AND CONVERT INTO DATAFRAME:\n")
features_names = oh_encoder.get_feature_names_out(['sex', 'smoker', 'day', 'time'])

encoded_df = pd.DataFrame(encoded_arr, columns=features_names)
print(encoded_df.head())

-> GET THE FEATURE NAMES AND CONVERT INTO DATAFRAME:

   sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0         1.0       0.0        1.0         0.0      0.0      0.0      1.0
1         0.0       1.0        1.0         0.0      0.0      0.0      1.0
2         0.0       1.0        1.0         0.0      0.0      0.0      1.0
3         0.0       1.0        1.0         0.0      0.0      0.0      1.0
4         1.0       0.0        1.0         0.0      0.0      0.0      1.0

   day_Thur  time_Dinner  time_Lunch
0       0.0          1.0         0.0
1       0.0          1.0         0.0
2       0.0          1.0         0.0
3       0.0          1.0         0.0
4       0.0          1.0         0.0

In [ ]:
store_OneValues = []
store_ZeroValues = []

def CHECK_EVERY_TICK_OF_CATEGORY(labels):
    store_OneValues.clear()
    store_ZeroValues.clear()

    for i in labels:
        if(i == 1):
            store_OneValues.append(i)
        else:
            store_ZeroValues.append(i)


def CHECK_CATEGORICAL_BINARY_VALUES(seprations):
    if seprations == 'sex_Female':
        CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['sex_Female'])

        print(f"-> TOTAL MALES: {store_ZeroValues.count(0)}")
        print(f"-> TOTAL FEMALES: {store_OneValues.count(1)}\n")
        
    elif seprations == 'smoker_No':
        CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['smoker_No'])

        print(f"-> TOTAL SMOKERS: {store_ZeroValues.count(0)}")
        print(f"-> TOTAL NON-SMOKERS: {store_OneValues.count(1)}\n")

    elif seprations == 'time_Dinner':
        CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['time_Dinner'])

        print(f"-> TOTAL LUNCH VISITS: {store_ZeroValues.count(0)}")
        print(f"-> TOTAL DINNER VISITS: {store_OneValues.count(1)}\n")


    elif seprations == 'day_Thur' or seprations == 'day_Fri' or seprations == 'day_Sat' or seprations == 'day_Sun':

        if seprations == 'day_Thur':
            CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['day_Thur'])
            print(f"-> TOTAL VISITS ON THURSHDAY: {store_OneValues.count(1)}")

        elif seprations == 'day_Fri':
            CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['day_Fri'])
            print(f"-> TOTAL VISITS ON FRIDAY: {store_OneValues.count(1)}")

        elif seprations == 'day_Sat':
            CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['day_Sat'])
            print(f"-> TOTAL VISITS ON SATURDAY: {store_OneValues.count(1)}")

        elif seprations == 'day_Sun':
            CHECK_EVERY_TICK_OF_CATEGORY(encoded_df['day_Sun'])
            print(f"-> TOTAL VISITS ON SUNDAY: {store_OneValues.count(1)}")


CHECK_CATEGORICAL_BINARY_VALUES('sex_Female')
CHECK_CATEGORICAL_BINARY_VALUES('smoker_No')
CHECK_CATEGORICAL_BINARY_VALUES('time_Dinner')

CHECK_CATEGORICAL_BINARY_VALUES('day_Thur')
CHECK_CATEGORICAL_BINARY_VALUES('day_Fri')
CHECK_CATEGORICAL_BINARY_VALUES('day_Sat')
CHECK_CATEGORICAL_BINARY_VALUES('day_Sun')

-> TOTAL MALES: 157
-> TOTAL FEMALES: 87

-> TOTAL SMOKERS: 93
-> TOTAL NON-SMOKERS: 151

-> TOTAL LUNCH VISITS: 68
-> TOTAL DINNER VISITS: 176

-> TOTAL VISITS ON THURSHDAY: 62
-> TOTAL VISITS ON FRIDAY: 19
-> TOTAL VISITS ON SATURDAY: 87
-> TOTAL VISITS ON SUNDAY: 76